name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.5.1
  - numpy=1.21.5
  - pandas=1.4.2
  - seaborn=0.11.2
  - IPython=8.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.9.2
  - jupyterlab=3.3.2
  - notebook=6.4.8
